package com.knoxhack.teslaarsenal;
import java.io.File;

import com.knoxhack.teslaarsenal.lib.Constants;

import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;





public class TeslaArsenalConfig {
	
	
	
	  public static Configuration config;
	    
	    public static int chargerCapacity = 50000;
	    public static int chargerPowerGen = 10;
	    public static int chargerTransferRate = 50;
	    public static boolean panelWaterDamage = true;
	    
	    public static void initConfig (File configFile) {
	        
	        config = new Configuration(configFile);
	        syncConfigData();
	    }
	    
	    /**
	     * Synchronizes the configuration file.
	     */
	    private static void syncConfigData () {
	        
	        chargerCapacity = config.getInt("PanelCapacity", "Charger", chargerCapacity, 0, Integer.MAX_VALUE, "The amount of power that can be stored by the charger.");
	        chargerPowerGen = config.getInt("PanelPowerGen", "Charger", chargerPowerGen, 0, Integer.MAX_VALUE, "The amount of power that is generated by the charger every tick.");
	        chargerTransferRate = config.getInt("PanelTransferRate", "Charger", chargerTransferRate, 0, Integer.MAX_VALUE, "The amount of power that can be pulled from the charger at a time.");
	        
	        if (config.hasChanged())
	            config.save();
	    }
	    
	    @SubscribeEvent
	    public void onConfigChange (ConfigChangedEvent.OnConfigChangedEvent event) {
	        
	        if (event.getModID().equals(Constants.MOD_ID))
	            syncConfigData();
	    }
	}

